[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["dt_greeting"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "dt_greeting"
  org = "chathurangasiriwardhana"
  version = "3.1.1"

